<a href="https://colab.research.google.com/github/kojiyam/information-theory/blob/main/it2_hamming_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ハミング符号

教科書だとインデックスは1から

Pythonはインデックスは0から始まるので，読み替え必要

Shift+Enterで実行

In [1]:
# 今回だけであればNumPyを使うほどではなく，若干可読性が下がるが
# 今後の講義でNumPyを使うので，混乱しないようにあえてNumPyベースで記載しています
import numpy as np

$ x_1, x_2, x_3, x_4 $

In [2]:
X = np.array([1,0,1,0], dtype='int8')

In [3]:
print(X)

[1 0 1 0]


$ c_1, c_2, c_3 $

In [4]:
c1 = np.fmod(X[0]+X[1]+X[2],      2)
c2 = np.fmod(     X[1]+X[2]+X[3], 2)
c3 = np.fmod(X[0]+X[1]     +X[3], 2)
C = np.array([c1, c2, c3], dtype='int8')

In [5]:
print(C)

[0 1 1]


In [6]:
W = np.concatenate([X, C])

In [7]:
print(W)

[1 0 1 0 0 1 1]


In [8]:
E = np.array([0,0,1,0,0,0,0], dtype='int8')
Y = np.fmod(W + E, 2)
print(Y)

[1 0 0 0 0 1 1]


## シンドローム

In [9]:
s1 = np.fmod(Y[0]+Y[1]+Y[2]     +Y[4]          ,2)
s2 = np.fmod(     Y[1]+Y[2]+Y[3]     +Y[5]     ,2)
s3 = np.fmod(Y[0]+Y[1]     +Y[3]+         +Y[6],2)
print([s1,s2,s3])

[1, 1, 0]


# 行列表記 7.1.4

In [10]:
G = np.array([[1,0,0,0,1,0,1],[0,1,0,0,1,1,1],[0,0,1,0,1,1,0],[0,0,0,1,0,1,1]], dtype='int8')
print(G)

[[1 0 0 0 1 0 1]
 [0 1 0 0 1 1 1]
 [0 0 1 0 1 1 0]
 [0 0 0 1 0 1 1]]


In [11]:
W2 = np.fmod(X @ G, 2)
print(W2)

[1 0 1 0 0 1 1]


In [12]:
H = np.array([[1,1,1,0,1,0,0],[0,1,1,1,0,1,0],[1,1,0,1,0,0,1]], dtype='int8')

## 検査方程式 (7.27)

In [13]:
np.fmod(W2 @ H.T, 2)

array([0, 0, 0], dtype=int8)

In [14]:
S = np.fmod(Y@H.T, 2)

In [15]:
print(S)

[1 1 0]
