<a href="https://colab.research.google.com/github/kojiyam/information-theory/blob/main/it6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

$ p I(p) = p \log_2 (1/p) $
を関数 `pI` として定義．pI(0)=0 としたいため．

単純にやると `0*np.log2(0)=nan` となる

In [ ]:
def pI_(p):
    if p==0:
        return 0
    else:
        return p*np.log2(1/p)
pI = np.vectorize(pI_) # numpy arrayを引数に取るため

## SLD. 43
$p_y = P_Y(y)$

In [ ]:
py = np.array([1/4, 0, 1/8, 1/2, 1/8])
np.sum(py)

1.0

$ p_y \log_2 (1/p_y) $

In [ ]:
print( pI(py) )

[0.5   0.    0.375 0.5   0.375]


$ \displaystyle \sum_{y} p_y \log_2 (1/p_y) $

In [ ]:
np.sum( pI(py) )

1.75

## SLD. 46 同時確率 $P_{X,Y}(x,y)$

In [ ]:
pxy = np.array([[1/8, 0, 1/16, 1/4, 1/16], [1/16, 1/16, 0, 1/4, 1/8]])
np.sum(pxy)

1.0

In [ ]:
print(pxy)

[[0.125  0.     0.0625 0.25   0.0625]
 [0.0625 0.0625 0.     0.25   0.125 ]]


### 同時エントロピー

$ H(X,Y) $

In [ ]:
np.sum( pI(pxy) )

2.75

## 周辺確率 $ P_Y(y) $ SLD. 48

$P_Y(y)$

In [ ]:
py = np.sum(pxy, axis=0) # 列方向に足す
print(py)

[0.1875 0.0625 0.0625 0.5    0.1875]


In [ ]:
np.sum( pI(py) )

1.9056390622295662

# 周辺確率 $ P_X(x) $

In [ ]:
print(np.sum(pxy, axis=1)) # 行方向に足す

[0.5 0.5]


## 条件付き確率 $P_{X|Y}(x|y) $ SLD. 50

In [ ]:
px1y = pxy/py
print(px1y)

[[0.66666667 0.         1.         0.5        0.33333333]
 [0.33333333 1.         0.         0.5        0.66666667]]


In [ ]:
print( pI(px1y) )

[[0.389975   0.         0.         0.5        0.52832083]
 [0.52832083 0.         0.         0.5        0.389975  ]]
